### ISSUE TITLE
Hello I am enrolled on create a web application with vue js Course I need to clone quiz 2 but I don't have access to clone

### ISSUE THREAD

**Issue by yehia67** [OpenClassrooms-Student-Center/Vue#5]
Quiz link:
https://openclassrooms.com/en/courses/5664336-create-a-web-application-with-vue-js/exercises/3714
Readme file I use:
https://github.com/OpenClassrooms-Student-Center/Vue/blob/master/part-2-quiz/README.md

First command to clone isn't working because I don't have access.

**Comment by bencodezen** [comment]
Hi @yehia67! That's weird. Could you post your error here? Cloning repos shouldn't have any permissions associated with them. Happy to help figure out what the issue is once we can see what the error is.

**Comment by Andriamanantoanina** [comment]
Hi @bencodezen I have the same issue, I cannot clone the repo because of permissions issue as well :/

**Comment by yehia67** [comment]
@bencodezen  This a screenshot of what I get.
![Screenshot from 2020-02-11 18-11-22](https://user-images.githubusercontent.com/21314724/74255107-153bd880-4cfa-11ea-8292-6b37dc23277c.png)

**Comment by bencodezen** [comment]
@yehia67 @Andriamanantoanina  It looks like you may need to connect your SSH key to the account. The following guide should help you.

https://help.github.com/en/github/authenticating-to-github/error-permission-denied-publickey

**Comment by Andriamanantoanina** [comment]
Yes, that solved the problem indeed, thank you @bencodezen !

**Comment by yehia67** [comment]
It works thank you.
